spring.application.name=M10_Spring_Consumo
# Habilita a interface visual do banco de dados no navegador
spring.h2.console.enabled=true

# Configura o caminho do banco e o login (sa)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=